### PR TITLE
[WEB] Feature: Open Candidate Detail

### PR DESCRIPTION
**Pull request by rrmdn**
## Summary

This PR is intended to add search-candidate functionality to rojak-ui-web.

### CODE REVIEW

**Comment by rrmdn** [comment]
@pyk please add some labels for this

**Comment by pyk** [comment]
cc @adrianha @y68 @CodeRiderz

**Comment by chi-putera** [comment]
Not sure about this one, buddy.

When you open `/candidates` page and you click one of the candidate, it should bring you to `<DefaultResult />` instead of creating new page result called `<OpenKandidat  />`.

The `<ResultGateway>` intended to be a wrapper to separate views between _special keywords_ (pairings, medias, candidates ) and specific keyword like `anies`, `ahok`, `ahok djarot`, `kompas` or even an `url` for news. It's there, because we would have a different looks / UI for those special pages and the default one.

We should create another _smart container_ in `<DefaultResult />`to manage whether a keyword is candidate, media, or news.

For example, if user type `ahok` in the search field, it will bring you to `/search/ahok`.
Then, this smart container inside `<DefaultResult />` should give you a `View` for a `candidate`.
It's the same for `Link`(s) listed in `/candidates` page, it should bring you to `/search/ahok` once you click it.

This way, we don't need to create another view / wrapper when user type `agus` in the search field.

What do you think ?

**Comment by pyk** [comment]
any update?

**Comment by rrmdn** [comment]
@CodeRiderz 

> The `<ResultGateway>` intended to be a wrapper to separate views between special keywords (pairings, medias, candidates ) 

Unfortunately, this `/candidate/:id` thingy is now another search term with special keywords:
screen shot 2016-11-06 at 8 12 33 am
(its now on stag: https://rojak-web.surge.sh)

**Comment by chi-putera** [comment]
Okay, I will accept this for now. Lets see if this will works with another features.

LGTM

**Review by pyk — APPROVED** [review]

**Comment by rrmdn** [comment]
Cool thanks

**Comment by pyk** [comment]
@rromadhoni ini udah aku bild juga di https://rojak.id ya 🙇

**Pull request merged**
