### PR TITLE
[rojak-ui-apps] Refactor APIService

### PR DESCRIPTION
**Pull request by esafirm**
Since we use `Dagger` for our dependency injection,`ApiService` creation should be handled in `Dagger` module to make it more modular.

It is also make `ApiService` more cleaner since it's only hold API schema.

### CODE REVIEW

**Comment by pyk** [comment]
cc @haydarai @anton46 @hidrodixtion @mychaelgo

**Review by mnafian — COMMENTED** [review]
AKhirnya master @esafirm turun gunung. Kalo gini jadi lebih rapi di servicenya 👍

**Comment by esafirm** [comment]
Ampun master @mnafian 🙏 mohon bimbinganya 😄

**Comment by anton46** [comment]
@esafirm Ampun kang

@pyk Kita bakalan ada login gak?

**Review by mychaelgo — APPROVED** [review]
Nice

**Comment by pyk** [comment]
@anton46 gak ada login mas.

Sep sep ini aku merge dulu yah 🙇

**Review by haydarai — APPROVED** [review]

**Review by pyk — APPROVED** [review]

**Pull request merged**
